name: Compile document

on:
  push:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: report.tex
      - name: Upload compiled file 
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: report.pdf
